# https://github.com/dependabot/dependabot-core/issues/1736
name: Dependabot
on:
  pull_request_target:
  workflow_dispatch:
jobs:
  pnpm-lockfile:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - run: pnpm i --lockfile-only
      - name: Set git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Push
        run: |
          git add pnpm-lock.yaml
          git commit -m "chore: dependabot[bot] update pnpm-lock.yaml" || echo "No changes to commit"
          git push
